# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Distillery.create!(distillery_name: "Bombay Sapphire", snippet: "A long standing favorite.", description: "If you drink gin, you must have had a Bombay at some point in your life. And it's fair to say, there's a lot of history with this distillery. Situated on a mill that dates back over 1,000 years, Bombay have built an wonderful modern distillery that sits within a Conservation Area and a Site of Special Scientific Interest.", website: "https://distillery.bombaysapphire.com/", tours: true)
Distillery.create!(distillery_name: "Cotswold Distillery", snippet: "A beautiful distilery in the wonderful Cotswolds.", description: "A multi-award winning distillery that has a great visitor experience. Along with gin, they are also producing Scotch Whisky and a cream liquor.", website: "http://www.cotswoldsdistillery.com/", tours: true)
Distillery.create!(distillery_name: "Lakes Distillery", snippet: "Who wouldn't want to drink gin from the Lake District.", description: "The Lakes is Cumbria's only distillery. This multi-award winner, produces vodka and whisky, alongside it's range of gins.", website: "http://www.lakesdistillery.com/", tours: true)
Distillery.create!(distillery_name: "Plymouth Distillery", snippet: "Plymouth's Black Friars distillery is the oldest working gin distillery in England", description: "One of the oldest gins in the country, and being located in the historic Royal Navy city, Plymouth gin hsd set sail on many a voyage. Along with their standard gin, they also produce a Navy Strength, which comes in at a punchy 57% ABV. ", website: "http://www.plymouthgin.com/", tours: true)
Distillery.create!(distillery_name: "Adnams Copper House", snippet: "This brewer also does a very fine gin.", description: "This long established brewer has been producing gins since 2010, and now offers a great little range. The most intriguing, but yet to be tried by the Inspector, is their Quince Gin (40%). ", website: "", tours: true)